### ISSUE TITLE
Rod of Shadows

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#278]
![](http://i.imgur.com/xBNdfNG.png)

is awesome!

**Comment by jeremygurr** [comment]
What? It's missing a spell? That looks like a vanilla bug. I'll look into it though.

**Comment by jeremygurr** [comment]
fixed.

**Comment by yrmvgh** [comment]
Still not working for me - same message. Possibly once the rod was generated, it was broken, and a new one would work but this one won't. ~shrug~

**Comment by Sandman25DCSS** [comment]
It works for me but does not spend MP so I can spam rod of shadows indefinately
