### ISSUE TITLE
Can't start games on http://crawl.homedns.org/

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#59]
I'm able to log into the lobby, but when I try to start a game I get the loading screen for a moment, then immediately get dropped back to the lobby.

I tried logging in with different accounts and got the same result.

**Comment by jeremygurr** [comment]
This should already be fixed. If not, then tell me.

**Comment by G0rg0** [comment]
Still not working, I just logged out and back in and get the same behavior.

**Comment by Sandman25DCSS** [comment]
The same for me, I cannot load my game.

**Comment by jeremygurr** [comment]
Ok it's finally back up.

**Comment by Sandman25DCSS** [comment]
Thank you! It works for me

**Comment by G0rg0** [comment]
Yep, working here as well, Thanks!
